export const LATEST_DATA_SUCCESS="LATEST_DATA_SUCCESS";
export const LATEST_DATA_FAILURE="LATEST_DATA_FAILURE";
export const DAILY_DATA_SUCCESS="DAILY_DATA_SUCCESS";
export const DAILY_DATA_FAILURE="DAILY_DATA_FAILURE";